### ISSUE TITLE
Question: additional winetricks for font installations

### ISSUE THREAD

**Issue by rik-shaw** [ferion11/LogosLinuxInstaller#10]
Question: you put a pile of fonts in, does Logos use those, or are you just being thorough? Also, adding the PowerPoint Viewer winetrick, again does that only give more fonts, or is that to help making a PDF or something else? Someone commented on PDF creation not working and I don't recall what we need to do to make it work?

**Comment by ferion11** [comment]
Well, it's more to make sure that the dotnet works better because of the Windows fallback font system (with possible others languages issues too), and allow the user to have more options, with cost of size less than 40MB. But after reading the "Why Logos’ Typography Matters", and review/rebuild many of my font system and uses, I'm re-thinking about this.

**Comment by ferion11** [comment]
Just to add one note here: a well-made installation of linux, already has several of these fonts installed on the system, or at least enough to not need it anymore, for LogosBible. So I'm thinking of removing those fonts from the installer.

**Comment by ferion11** [comment]
The v2.0 now only use `corefonts`, just to make sure that we have the basics fonts: https://github.com/ferion11/LogosLinuxInstaller/blob/6c8f01cea4fbdc100a991bb9a4b93c22f12eb3e4/install_AppImageWine_and_Logos.sh#L548-L554
