### ISSUE TITLE
Question: disable-winemenubuilder?

### ISSUE THREAD

**Issue by rik-shaw** [ferion11/LogosLinuxInstaller#11]
Question: does the "disable-winemenubuilder" reg key just make wine not create launchers? Or what does this address?

**Comment by ferion11** [comment]
I would like to disable any wine auto-creating, non controlled, system. Because it can make a mess on your user configuration, like making all text files associations with notepad.exe (and many others, without asking). But the main motivation is to not conflict with the local wine installation of your system, which can be used at the same time. The idea original was to leave everything in the same directory, separated into sub-directories (one for AppImage, another to LogosBible wine bottle, ...), like one big portable app. Perhaps on the future.
