### ISSUE TITLE
Help with Installation

### ISSUE THREAD

**Issue by arcanemuse** [ferion11/LogosLinuxInstaller#138]
My library is over 70 gigs.  Logos crashed numerous times and I just kept restarting it and running it again and again slowly making progress.  After over 24 hours I had it down to around 10 gigs or so.  I was almost there.  Now it starts up, loads, says one of my resources that was open before is no longer in my library, sits there for a moment or two and then crashes.  It won't stay open for even two minutes now before crashing.  I guess I should perhaps just admit that you can't run a windows program as complex as Logos on Linux and be done with it.  I'll leave it for now in case somebody has a brilliant suggestion that doesn't involve the use of a sledge hammer or a firearm. LOL

**Comment by thw26** [comment]
Hey @arcanemuse, sorry I haven't responded yet.

There are some tricks up our sleeves we can attempt.

The best way to get immediate help is through the Telegram/Matrix group if you have access to it.

There are a few things that could go wrong. We can usually be quicker to help there. Github isn't necessarily the best place to report install problems but rather than bugs or feature requests for the script.

My library for reference is a little over 30G if I recall, but there are others with more. I think you're the first I've heard with a library of that size though.

**Comment by thw26** [comment]
I am closing this issue. If you need help, please don't hesitate to ask.
