### ISSUE TITLE
Congrats on the wonderful 2.0 Release!

### ISSUE THREAD

**Issue by aaylnx** [ferion11/LogosLinuxInstaller#14]
Daniel,

I want to give you a hearty congratulations on the new 2 series release. I visited the Git page a few days ago when the portable version was available. I was very, very impressed by the fact that . . .well. . .it was completely portable. After installing it on a laptop, I was able simply to copy the folder over the network to my desktop machine and voila it just worked.

I notice that the previous portable version is removed, but it looks like the new install will still be portable. The primary difference seems to be that the new installer pulls down all of the Microsoft stuff etc rather than having that (conveniently) bundled. Convenient or not, long term it's probably much better to have the user pull down all of that stuff themselves.

I installed the new version and my system is busy indexing. Is it me or have you also figured out how to get rid of various bugs we've seen in the install process.  The initial crash of the installer seems to no longer be an issue. Also, the Logos indexing icon is now showing up in my desktop panel whereas I don't think it stayed down there before. Nice! Moreover, it just seems to be indexing much smoother even though my system is not done yet. 

I have a couple of questions. First, what exactly is the purpose of your controlPanel.sh? 

Secondly, when my setup is finished installing (or rather indexing at this point), will it be as portable as the previous version? Will I simply be able to move LogosBible_Linux_P to another machine? That would be perfect!

Thanks again for all of your hard work. It shows!!!

Adam York

**Comment by ferion11** [comment]
> Daniel,
> 
> I want to give you a hearty congratulations on the new 2 series release. I visited the Git page a few days ago when the portable version was available. I was very, very impressed by the fact that . . .well. . .it was completely portable. After installing it on a laptop, I was able simply to copy the folder over the network to my desktop machine and voila it just worked.

Thanks. The portable version had a serious problem: when updating, wine looked for the username who installed LogosBible, so the different username would throw an error in the updates. I need to patch the Wine source code for this to work like intended.

> I notice that the previous portable version is removed, but it looks like the new install will still be portable. The primary difference seems to be that the new installer pulls down all of the Microsoft stuff etc rather than having that (conveniently) bundled. Convenient or not, long term it's probably much better to have the user pull down all of that stuff themselves.

Yes. There is a username problem, and some restrictions on the EULA as well (because of that, I can't officially host it). Maybe I'll come back with it after getting a better and automated way to compile wine with patches and make one for this, as it has a faster installation (I created one new repository that creates something halfway in this direction, a Wine Bottle 64bits with dotnet48, fonts and other fixes that Logos needs, https://github.com/ferion11/wine64_bottle_dotnet/releases ).

> I installed the new version and my system is busy indexing. Is it me or have you also figured out how to get rid of various bugs we've seen in the install process. The initial crash of the installer seems to no longer be an issue. Also, the Logos indexing icon is now showing up in my desktop panel whereas I don't think it stayed down there before. Nice! Moreover, it just seems to be indexing much smoother even though my system is not done yet.

No, the new default is the wine-staging-v5.11, and I'm just applying the fixs that are described in the installation of wasta-wine with LogosBible (credits for the creators of the wasta-wine and the guide, and for the people that are reporting and the ones fixing bugs at https://bugs.winehq.org ).

> I have a couple of questions. First, what exactly is the purpose of your controlPanel.sh?

Let's say that some LogosBible update fails and has a corrupted installation, so the user can simply use `controlPanel.sh`, go to `Add and Remove Programs`, remove LogosBible and use the `Install` button (which is on the same screen) to install a new version directly (without using commands).

> Secondly, when my setup is finished installing (or rather indexing at this point), will it be as portable as the previous version? Will I simply be able to move LogosBible_Linux_P to another machine? That would be perfect!

Yes, just like the old portable version. This applies even to installations done without AppImage (it can be used with wasta-wine too, instead of the AppImage), using the `install_AppImageWine_and_Logos.sh`, but in this case it will need the same dependencies (like the wine) and username on the other machine as well. Having the same problem that it can only be moved to a user of the same username on another machine (because of this the "Portable" in the name has been shorted to just "P").

> Thanks again for all of your hard work. It shows!!!
> 
> Adam York

Thanks you too.

By the way, each installation mode is test and images is generated now, like in: https://github.com/ferion11/LogosLinuxInstallTests/releases/tag/continuous
we have the images for wine-staging-v5.11 (1- AppImage, 2-Native wine32, 3-Native wine64), but testing the native wine-staging-v5.13 only the installation with AppImage worked (because it has the wine-staging-v5.11 inside):
https://travis-ci.com/github/ferion11/LogosLinuxInstallTests/builds/177848581

**Comment by aaylnx** [comment]
Outstanding!  Just getting to this post now.  Thanks for all of the feedback.  Quite interesting!

**Comment by ferion11** [comment]
Just to add some more note here too (so don't worry):

* Looking at the patched code we have the use of getuid function (just like in PlayOnLinux version):
https://github.com/Tk-Glitch/wine-tkg/blob/1aa9bfcd7996262e0b99af941bb719f7efe7bf9e/libs/wine/config.c#L417-L422
* But at the vanilla wine, we have the use of USER variable:
https://github.com/wine-mirror/wine/blob/6d801377055911d914226a3c6af8d8637a63fa13/libs/wine/config.c#L281-L285

I'm preparing my own Wine build from the code ([here](https://github.com/ferion11/f11_wine_builder)) to make one new AppImage with it fixed, so the "P" version can become "Portable" again.

**Comment by ferion11** [comment]
> Just to add some more note here too (so don't worry):
...
> So, some patch is changing the default behavior. I'm preparing my own Wine build from the code ([here](https://github.com/ferion11/f11_wine_builder)) to make one new AppImage with it fixed, so the "P" version can become "Portable" again.

I tested it now, but unfortunately it didn't work. During the installation it uses the user of the USER variable, but at the time of running LogosBible, it changes the user. So, I need to further analyze the code and make an extra patch for this to work.

**Comment by aaylnx** [comment]
> > Just to add some more note here too (so don't worry):
> > ...
> > So, some patch is changing the default behavior. I'm preparing my own Wine build from the code ([here](https://github.com/ferion11/f11_wine_builder)) to make one new AppImage with it fixed, so the "P" version can become "Portable" again.
> 
> I tested it now, but unfortunately it didn't work. During the installation it uses the user of the USER variable, but at the time of running LogosBible, it changes the user. So, I need to further analyze the code and make an extra patch for this to work.

**Comment by aaylnx** [comment]
Nice! I will look out for it.

After upgrading to 8.15 yesterday, WINE kept crashing. I should have just used your controlPanel.sh to remove the installer, and downloaded an older one and installed that. I will remember that for next time.

Also, I need to remember that it's not necessary to keep re-downloading all gigabytes and gigabytes of files each time you do a new install. I haven't yet tried the approach listed [here](https://wiki.logos.com/quick_installation_onto_multiple_computers) for a "Quick Install", but hopefully method 2 will work and this will save a lot of time downloading and indexing. We shall see. I may test it out later today.

**Comment by aaylnx** [comment]
Daniel, and anyone else reading this!, I don't know if you are aware of the Telegram group that exists which discusses running Logos on Linux, but you would certainly be welcome in there. There's a lot of good discussion going on. I have recently been reporting to folks in there regarding your progress. I believe it's encouraging them. Link is [here](https://t.me/linux_logos).

**Comment by ferion11** [comment]
> Daniel, and anyone else reading this!, I don't know if you are aware of the Telegram group that exists which discusses running Logos on Linux, but you would certainly be welcome in there. There's a lot of good discussion going on. I have recently been reporting to folks in there regarding your progress. I believe it's encouraging them. Link is [here](https://t.me/linux_logos).

Well, about the recent bugs, I would like to be able to do something more relevant, but these changes that are happening with wine 5.x can only be solved at https://bugs.winehq.org. The truth is that Wine version 4.x has been abandoned (literally), and version 5.x has a lot of code imported from Proton Wine that developers still don't quite understand and are trying to work with.
Big changes are happening everywhere (on vanilla wine, on wine-staging, inside the code of LogosBible too, like the last and fast update that break wine-v4.x), and adapting to them will take some time.

What I did, with version 2.0 of this installer, was to create an easier way to test by making independent installations that can be backup-ed  just by copying the directory. But I haven't solved any current problem. Without diving into the Wine's code, that's the best that I could do. And even after that, I would need to migrate my system to a multilib installation, to make contributions.
For a software developer, working without being able to compile the code locally within an IDE to test changes is highly stressful and time consuming (working with unstable software like current Wine only adds to the problem), even my remote wine compilation took more than 70 attempts to get one configuration that works (and take more than 30 minutes to compile it).
That said, at this point in time, unfortunately, I'm completely useless. Instead of encouraging them, I would be more like the Book of Ecclesiastes.

**Comment by aaylnx** [comment]
Sounds good. None of the folks in the Telegram channel are WINE developers though. Just users of your and Rik's methods of installation. Users who are testing things out, trying to get Logos to install under Linux etc.

Yes, your 2.0 approach is nice in so many ways. It's definitely allowing me to easily keep snapshots and test things out before moving ahead with an upgrade that breaks things badly.

**Comment by ferion11** [comment]
> Sounds good. None of the folks in the Telegram channel are WINE developers though. Just users of your and Rik's methods of installation. Users who are testing things out, trying to get Logos to install under Linux etc.
> 
> Yes, your 2.0 approach is nice in so many ways. It's definitely allowing me to easily keep snapshots and test things out before moving ahead with an upgrade that breaks things badly.

Thanks, i will try then :)

**Comment by jg00dman** [comment]
Just a thought... if the EULA is the issue, it might be that the portable version gets built by the script on the users system?

**Comment by ferion11** [comment]
> Just a thought... if the EULA is the issue, it might be that the portable version gets built by the script on the users system?

Yes, the issue is in publicly hosting it, not downloading and using it.
