### ISSUE TITLE
What about an upgrade script?

### ISSUE THREAD

**Issue by jg00dman** [ferion11/LogosLinuxInstaller#17]
Daniel, 
Just a thought, what do you think about adding a Logos upgrade script?
It might:

- update scripts in installation folder e.g. Logos.sh
- download newer wine appimages
- update Logos itself by moving the old Data, Documents and Users folders to a backup location, running the MSI installer and then putting them back (this would be a good temporary work around for constantly having to download resources after each update) n.b. I've tried this and it works.
- check for the availability of an update (perhaps Logos.sh could do this and notify the user?)

John

**Comment by jg00dman** [comment]
Here's how I do it...
Move user data out of logos directory so it isn’t overwritten.
`mkdir $HOME/logos-app-data `
 
`mv $HOME/.wine-logos/drive_c/users/$USER/Local\ Settings/Application\ Data/Logos/Data $HOME/logos-app-data/Data && mv $HOME/.wine-logos/drive_c/users/$USER/Local\ Settings/Application\ Data/Logos/Documents $HOME/logos-app-data/Documents && mv $HOME/.wine-logos/drive_c/users/$USER/Local\ Settings/Application\ Data/Logos/Users $HOME/logos-app-data/Users`

Archive or backup your .wine-logos folder. Ideally also your user data if you have disk space.

Run the installer or restore the user data and then you can do the built in update.
`WINEPREFIX=$HOME/.wine-logos/ WINESERVER=/opt/wasta-wine/bin/wineserver WINE=/opt/wasta-wine/bin/wine /opt/wasta-wine/bin/msiexec /i /path/to/logosinstaller.msi`

Restore user data
`mv $HOME/logos-app-data/Data/* $HOME/.wine-logos/drive_c/users/$USER/Local\ Settings/Application\ Data/Logos/Data/ && mv $HOME/logos-app-data/Users/* $HOME/.wine-logos/drive_c/users/$USER/Local\ Settings/Application\ Data/Logos/Users/ && mv $HOME/logos-app-data/Documents/* $HOME/.wine-logos/drive_c/users/$USER/Local\ Settings/Application\ Data/Logos/Documents/`

**Comment by jg00dman** [comment]
As the user base grows, the update notification could state whether we consider the upgrade 'untested' (for the brave) or 'recommended' (well tested).

**Comment by ferion11** [comment]
> Just a thought, what do you think about adding a Logos upgrade script?

Well, it would be hard to keep the updater updated. And the ideia behind this "P" version is to be easy to manual do things like that without depending of other script.

> * update scripts in installation folder e.g. Logos.sh

What I'm thinking, would be the update be simple like this:
1- Make one new skel of the same installation type (64bits or 32bits)
2- Copy from the old installation `data` directory, **just the wineBottle directory** and the AppImages (you can have many, or none)
3- And only if you are using AppImage, then run `$ ./Logos.sh selectAppImage` to re-select it.
Then if you aren't using AppImage, you just need to copy the wineBottle directory to the new generated skel, and it will be the updated version.

> * download newer wine appimages

Well, you can use any AppImage of wine you want now, not just the ones that I made, and having a lot of choices is better than having fixed options. The `selectAppImage` option can copy the AppImage to the data directory too, and the switch is very easy with it.

> * update Logos itself by moving the old Data, Documents and Users folders to a backup location, running the MSI installer and then putting them back (this would be a good temporary work around for constantly having to download resources after each update) n.b. I've tried this and it works.
> * check for the availability of an update (perhaps Logos.sh could do this)

Well, I want to keep the installation more independent possible, because the way of LogosBible installation works can change. This solution is projected to be so generic that you can copy your wineBottle `$HOME/.wine-logos` to a new skel and it will works just like the installation that you made, and if you want to test one other wine version then is just easy like getting one AppImage, running `$ ./Logos.sh selectAppImage` and done! Don't matter what the directory the user used in the installation of LogosBible, it will work.

**Comment by ferion11** [comment]
To make these operations easier, I added 2 more options on `Logos.sh`:

1- `dirlink` creates a symbolic link, at the same directory of `Logos.sh`, to the LogosBible installation directory (inside the wineBottle), to facilitate manual copying: https://github.com/ferion11/LogosLinuxInstaller/commit/1f154c9a59c2f1414fe0c2c2126c8338ab4be615

2- `removeAllIndex` removes all index and catalog files as reported by Frank Sauer (to allow the redo the whole index files to fix possible issues): https://github.com/ferion11/LogosLinuxInstaller/commit/420a371212892dcf603564765330535665c6c137

**Comment by ferion11** [comment]
Adding more notes on these 2 points:

> * update Logos itself by moving the old Data, Documents and Users folders to a backup location, running the MSI installer and then putting them back (this would be a good temporary work around for constantly having to download resources after each update) n.b. I've tried this and it works.

I hope we can identify and fix this issue (of the files been removed at update), so that we don't need to add more workaround solutions.

> * check for the availability of an update (perhaps Logos.sh could do this and notify the user?)

LogosBible can notify the user of its updates. As for the version of the script, I think the update should happen for necessity only. Since there are many updates, and not everyone uses or needs these new features.
You can see this in: https://community.logos.com/forums/t/121.aspx?PageIndex=51
on the user Purist logs we have:
```
...
System information:
    Wine build: wine-4.18
    Platform: i386
    Version: Windows 5.1 (0)
    Host system: Linux
    Host version: 5.4.0-47-generic
```
and he is happy with his installation, especially now that he has learned another way to fix his installation.

**Comment by jg00dman** [comment]
I think we will soon have a fix for the data loss when updating issue. In that case Logos will update itself. The fix seems to be in proton experimental so I need to do some regression testing to isolate the patch. https://bugs.winehq.org/show_bug.cgi?id=49767
