### ISSUE TITLE
Running the Script by Double-Click on KDE Automatically Looks for KDialog Rather Than Switching to Zenity

### ISSUE THREAD

**Issue by jg00dman** [ferion11/LogosLinuxInstaller#186]
I set the script to executable and then double clicked it in kubuntu. The window manager crashed and I had to log in again. I repeated this to confirm. I expected a GUI mode install.

**Comment by thw26** [comment]
Possibly related? https://github.com/ferion11/LogosLinuxInstaller/issues/161

**Comment by jg00dman** [comment]
I'm not sure how to gather logs to be honest... not from a double click. It works in the terminal which is where I'd get the log from.

**Comment by thw26** [comment]
Okay. We probably just need to set up logging in the script so that GUI installs can get them. I imagine a variable would be sufficient that is set on GUI install or set with a flag that stores the install log in a file.

**Comment by thw26** [comment]
I've confirmed this bug.

It appears to be crashing on the creation of the zenity window at `chooseProduct()`.

Zenity windows are created fine from a terminal. Something must not be getting passed as required…

**Comment by thw26** [comment]
It is failing at this line:

https://github.com/ferion11/LogosLinuxInstaller/blob/12c2fcdfe4dc129d08a1077d393b0a6d4acee12a/LogosLinuxInstaller.sh#L511C1-L511C32

**Comment by thw26** [comment]
Okay. With #190 the script no longer crashes the desktop, but the script will not succeed on installing because double-clicking in KDE looks for kdialog by default, probably setting a variable, `$DIALOG`, to kdialog. This is also the name of the dialog variable we use. A simple solution might be to rename our variable. A fuller solution would be to implement #136.

**Comment by thw26** [comment]
Another possibility would be that the script looks for kdialog because the script is run from KDE.

https://github.com/ferion11/LogosLinuxInstaller/blob/494b1e1d29f30e9f5d0af855f3ee5eacf087c1af/LogosLinuxInstaller.sh#L118-L127

Thus what we need to do is disable kdialog in this check.

---

Testing.
