### ISSUE TITLE
Wrong keyboard-layout

### ISSUE THREAD

**Issue by diakonostheou** [ferion11/LogosLinuxInstaller#3]
Thanks a lot for this script. I tried it with Linux Mint 19.3 Cinnamon. It worked well but it didn´t adopt my german desktop environment (for example: keyboard layout). Is there a possibilty to change the keyboard and language settings in your script?

**Comment by ferion11** [comment]
Hi! The bug here is in the **wine with dotNET** ([see link](https://bugs.winehq.org/show_bug.cgi?id=47277)).
The workaround at that time, was using "LC_ALL=C", that change the language to default.
If you wanna try, you can just remove the "LC_ALL=C" from your Desktop "Logos.sh" file:
* from (line 7, i guess):
`LC_ALL=C wine /PATH/TO/LOGOS_EXE`
* to (using your system configuration):
`wine "$LOGOS_EXE"`
* or (to force "German" language):
`LC_ALL=de_DE.utf8 wine /PATH/TO/LOGOS_EXE`

The **keyboard layout** is another question: **A lot of wine programs use the X keyboard layout instead of the window manager's layout. You have to change it by running "setxkbmap":**
* For change layout to German:
`setxkbmap 'de'`
* For change layout to Swiss German:
`setxkbmap 'ch(de)'`
* For Swiss German and German (multiples layouts):
`setxkbmap 'ch(de),de'`
* For Switching Between Keyboard Layouts using "Alt-Shift":
`setxkbmap -option 'grp:lalt_lshift_toggle'`
* For Swap “Caps Lock” and “Ctrl” Keys:
`setxkbmap -option 'ctrl:swapcaps'`
* List all valid German kbd layouts, variants and toggle options (to use with setxkbmap):
`sed '/! variant/,/^$/!d;/Germany/!d' < /usr/share/X11/xkb/rules/evdev.lst`

Since the configuration is not permanent (lose at boot time), and is useful in other applications, I have to recommend you to configure your xorg.conf with this configuration (NOTE: using your ~/.bashrc for setxkbmap, will result in error). On the Linux Mint, I guess you have to change 2 files "/etc/default/keyboard" and "/etc/X11/xorg.conf"
But if the LogosBible is the only one using this, you can just put the line of "setxkbmap" that work better for you, before the line that call "wine" (line 7, i guess) in your Desktop "Logos.sh" file.

**Comment by ferion11** [comment]
LC_ALL=C removed at a43d6f7229a140c910f5eff72e715c2d9a39beb8 now that the new default is wine 5.x
