### ISSUE TITLE
Launch Logos.sh provides wine config only

### ISSUE THREAD

**Issue by Gene-W** [ferion11/LogosLinuxInstaller#4]
Hello,

When I run Logos.sh, I get is the wine configuration pop up and selecting either ok or cancel closes the pop up and ends the launch.

Ive tried to run Logos with terminal and by double clicking and both methods give the same result.

I'm running Manjaro 64bit.

Thank you.

**Comment by ferion11** [comment]
Sorry! Between 10 days and 2 days ago ([when I fixed it](https://github.com/ferion11/LogosLinuxInstaller/commit/e743c25538ac49a500010cee4bd259da9208cad6)), my script have a broken link to the LogosBible Installer.
Please, download the last version (now v1.3) os the scripts [HERE](https://github.com/ferion11/LogosLinuxInstaller/releases/tag/v1.3):

1. Use the "Uninstall_AppImageWine_and_Logos.sh" to remove all
2. Use the new "Install_AppImageWine_and_Logos.sh" to make the installation again.

**Comment by Gene-W** [comment]
Amazing! After fighting with this for so long, it's up and it is running! Thank you for all of your work!!

**Comment by ferion11** [comment]
Glad to help.
Remember:
* When you need Indexing you LogosBible library, close the LogosBible and use the `LogosIndexing.sh` script (it just change the profile to winxp, run indexing, and go back to win7 profile, but all with GUI feedback). Note that, sometimes, small changes on the library have a working indexing (on win7 profile) without using the script.
* You can use the script `Update_WineAppimage.sh` to update your wine too.

**Comment by Gene-W** [comment]
Very good, indexing worked well. Is the `Update_WineAppimage.sh` used for updating Logos when there's an update available, or will that happen within Logos itself?

**Comment by ferion11** [comment]
The LogosBible can update itself. Just remember of complete all update (include library), before indexing again. Sometimes, the new LogosIndexer don't work well with old library.
The `Update_WineAppimage.sh` is to update only the wine that the LogosBible is using. It will keep working with the current wine version (the news versions is just to improve performance and bugfix some features).

**Comment by Gene-W** [comment]
I'm sorry to bother you with this as I believe it's been caused by some updates to Manjaro today. When I try to launch Logos.sh now, I see the following error:

`Something went wrong trying to read the squashfs image.

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory`

If I try to run it with --appimage-extract as suggested, it repeats the same error.

I checked the FUSE github and github wiki, but I can't find this particular error. I also searched the Manjaro forums and Google, have switched kernels, and rebooted a few times after trying these things.

Is it best to once more remove everything and start fresh?

**Comment by ferion11** [comment]
Don't worry, I like to help :)

It's because your system FUSE installation is broken (you probably can't mount pendrives too).
I couldn't find Manjaro's bugtracker, but Manjaro is ArchLinux based, then I have looked on bugs.archlinux.org and found this [HERE](https://bugs.archlinux.org/task/61261?string=fuse&project=1&type%5B0%5D=&sev%5B0%5D=&pri%5B0%5D=&due%5B0%5D=&reported%5B0%5D=&cat%5B0%5D=&status%5B0%5D=open&percent%5B0%5D=&opened=&dev=&closed=&duedatefrom=&duedateto=&changedfrom=&changedto=&openedfrom=&openedto=&closedfrom=&closedto=). And if that is the case, if you install the package "**fuse3**" in your package manager, then the bug should be workaround.

**Comment by Gene-W** [comment]
I do see fuse 2 and fuse 3 installed, so I refreshed both installations and it didn't work. :(

**Comment by ferion11** [comment]
Then the bug of FUSE after update ins't that one.
Try to reinstall the packages: **squashfuse** and **squashfs-tools**

If it don't work, then let's get some information with:
1- `$ zcat /proc/config.gz | grep FUSE`
2- `$ lsmod | grep fuse`
3- `$ fusermount -V`
4- `$ cat /etc/group | grep fuse`
5- `$ cat /etc/passwd | grep fuse`
And we will work with that information in mind :)

**Comment by Gene-W** [comment]
Really appreciate your time and help.
**squashfuse** wasn't there so I installed it, **squashfs-tools** was there and I reinstalled it just in case, then I rebooted.

1 - `zcat /proc/config.gz |grep FUSE
CONFIG_FUSE_FS=m
CONFIG_AUFS_BR_FUSE=y`

2- `lsmod | grep fuse
fuse                  139264  3`

3- `fusermount -V
fusermount version: 2.9.9`

4 and 5 didn't produce any output :)

**Comment by ferion11** [comment]
Ok! Install the package **unionfs-fuse** too, just in case.
* Reboot and get the result of:
`$ dmesg | grep fuse`
* Test the **Logos.sh** too :)

**Comment by Gene-W** [comment]
Unfortunately, **Logos.sh** gave the same AppImage/FUSE error. However...maybe a clue!

`dmesg | grep fuse
dmesg: read kernel buffer failed: Operation not permitted`

**Comment by ferion11** [comment]
This message maybe is just permission on `dmesg` side. Try the commands using **sudo**:
* `$ sudo dmesg | grep fuse`
* `$ sudo dmesg | grep erro`

**Comment by Gene-W** [comment]
Ah, ok.
`sudo dmesg | grep fuse
[   59.544221] fuse: init (API version 7.31)
[   59.544248] *** VALIDATE fuse ***
[   59.544251] *** VALIDATE fuse ***`

**Comment by ferion11** [comment]
Let's review the information:
* `zcat /proc/config.gz | grep FUSE`:  CONFIG_FUSE_FS=m CONFIG_AUFS_BR_FUSE=y
Your system use **fuse** like module
* `lsmod | grep fuse`: fuse 139264 3
Your system have the module **fuse** loaded.
* `fusermount -V`: fusermount version: 2.9.9
Your system use the **2.9.9 version**
* `cat /etc/group | grep fuse` and `cat /etc/passwd | grep fuse`: ""
Your system don't have a user or a group to use **fuse**
* `sudo dmesg | grep fuse`: *** VALIDATE fuse ***
You system don't give error message on fuse module loading.

Then, we can try create one group to fuse, and put your user inside it:
`$ sudo groupadd fuse`
`$ sudo usermod -aG fuse $(whoami)`
Reboot and try Logos.sh again.

**Comment by Gene-W** [comment]
Logos is indeed a stubborn program, or Manjaro is an unwilling partner. :)
Strange though that it worked for a day or 2.

`sudo groupadd fuse
groupadd: group 'fuse' already exists`

`sudo usermod -aG fuse $(whoami)` shows a list of available options.

And for fun...
`at /etc/group | grep fuse
fuse:x:1003:irish`

But `cat /etc/passwd | grep fuse` still doesn't show any result.

**Comment by ferion11** [comment]
It's don't have nothing to do with Logos itself or Wine. But is the Manjaro that is ArchLinux based. The ArchLinux have the rule "the last version of all software is more stable" (but that is not true for all). Resulting in the ArchLinux users being the first to find the bugs of all software. And the solution that I made use the wine from AppImage, that need the working fuse.

We have two choices:
* Wait for one Manjaro update that will solve the problem.
Or
* Use the Manjaro wine-staging:
1- Install the **wine-staging** from package manager
2- Change the Logos.sh to use the native wine:
To comment the use of AppImage wine (just one time):
`sed -i '/export PATH/c #export PATH=:\$PATH' $HOME/Desktop/Logos.sh`
To use the ~/.wine32 with the native wine (just one time):
`sed -i "s/LC_ALL/WINEPREFIX=~\/.wine32 LC_ALL/g" $HOME/Desktop/Logos.sh`
Now the **Logos.sh** should be using the native wine instead of the AppImage.
You can execute the **Logos.sh** now:
`$HOME/Desktop/Logos.sh`

**Comment by Gene-W** [comment]
And I came off of Mint, it wasn't playing nicely with my graphics so I made a switch.
When I look at the **wine-staging** in package manager, I see these options. My guess is select all, but I don't want to break other things. :)
![wine_options](https://user-images.githubusercontent.com/19363963/73289998-ed2e7e80-41fd-11ea-8593-f8f74c36f694.png)

**Comment by ferion11** [comment]
* lib32-giflib is for open images in gif format: is good to install.
* lib32-opencl-icd-loader is for opencl: is good to install (Logos don't use it, but can use someday)
* lib32-libva is for play videos: is good to install too
* lib32-gtk3 is just for wine theme: is good for install because other 32bits software use it too.
* lib32-gst-plugins-base-libs is for playing some videos too: is good to install
* vkd3d and lib32-vkd3d is for vulkan support: you don't need now, but is good to install too.
* samba is for Windows sharing files network: is good to install too
* dosbox is for run old DOS apps: is good to install too.

You can select all, you system is safe this time. Nothing should break :)

**Comment by Gene-W** [comment]
You have been extremely patient and helpful and I can't say enough how much I appreciate it. Even more, I'm learning some things along the way that hopefully will help in other things later on!

Well, we did get rid of the old FUSE error, and now I see this which maybe isn't quite as bad :)
At first, I saw the Wine Gecko popup and canceled it, then got this:

`'/home/irish/Desktop/Logos.sh' 
000b:fixme:winediag:__wine_start_process Wine Staging 5.0 is a testing version containing experimental patches.
000b:fixme:winediag:__wine_start_process Please mention your exact version when filing bug reports on winehq.org.
**0009:err:module:__wine_process_init L"C:\\windows\\system32\\.exe" not found**`

Have been searching and looking for clues on that but what I'm finding so far do not apply.

**Comment by ferion11** [comment]
I have made one script to remake Logos.sh to use native wine:
https://github.com/ferion11/libsutil/releases/download/logos_01/change_Logos_to_navive.sh
Download and execute it, and try again :)
`wget -c https://github.com/ferion11/libsutil/releases/download/logos_01/change_Logos_to_navive.sh`
`chmod +x change_Logos_to_navive.sh`
`./change_Logos_to_navive.sh`
`$HOME/Desktop/Logos.sh`

**Comment by ferion11** [comment]
I have 2 scripts now, here:
https://github.com/ferion11/libsutil/releases/tag/logos_02
* the `change_Logos_to_native.sh` is to change **Logos.sh** to use native wine
* the `change_Logos_to_Appimage.sh` is to change **Logos.sh** back to use AppImage

**Comment by ferion11** [comment]
The problem here is `"C:\\windows\\system32\\.exe" not found**`
The old **Logos.sh** don't have a valid path to the **Logos.exe** executable. Then I made the script to find it using `find $HOME/.wine32 -name Logos.exe |  grep "Logos\/Logos.exe"` to set **Logos.exe** location on the **Logos.sh** script :)
Then, after running `change_Logos_to_native.sh`, the Logos.sh should work :)

**Comment by Gene-W** [comment]
Very sorry, something I'm not doing right. I downloaded to desktop and used terminal:

`$ sudo chmod +x ~/Desktop/change_Logos_to_native.sh
$ ~/Desktop/change_Logos_to_native.sh
$ ~/Desktop/Logos.sh
000b:fixme:winediag:__wine_start_process Wine Staging 5.0 is a testing version containing experimental patches.
000b:fixme:winediag:__wine_start_process Please mention your exact version when filing bug reports on winehq.org.
0009:err:module:__wine_process_init L"C:\\windows\\system32\\.exe" not found`

**Comment by ferion11** [comment]
That is strange :)
Post the content of this command here:
`cat ~/Desktop/Logos.sh`
and just to be sure, this too:
`find $HOME/.wine32 -name Logos.exe | grep "Logos\/Logos.exe"`

By the way: You don't need use **sudo** anymore (it's just to execute commands using **root** user).

**Comment by Gene-W** [comment]
It is strange...Thanks for clarification on sudo, I was trying everything I could think of to get it to work :)

`cat ~/Desktop/Logos.sh
#!/bin/bash
# Save IFS
IFS_TMP=$IFS
IFS=$'\n'

WINEPREFIX=/home/irish/.wine32 LC_ALL=C wine ""

# restore IFS
IFS=$IFS_TMP`

The `find $HOME/.wine32 -name Logos.exe | grep "Logos\/Logos.exe"` doesn't produce any results. :(

**Comment by ferion11** [comment]
For some reason you LogosBible has been uninstalled (removed). I will remake the install script to install without using AppImage. Just a few minutes :)

**Comment by Gene-W** [comment]
Well I have been known to break things in order to learn how to fix them! :)

**Comment by ferion11** [comment]
Here: https://github.com/ferion11/libsutil/releases/tag/logos_01
Download: https://github.com/ferion11/libsutil/releases/download/logos_01/Install_Logos.sh
I hope, this time it will work :)

**Comment by Gene-W** [comment]
Great news! It's up and running, fully indexed and can open resources. I can't say thank you enough for all of your help!! I'll have an opportunity to put it to work tomorrow for sure.

**Comment by ferion11** [comment]
Good! You can still use the `LogosIndexing.sh` to indexing, but first, to be sure, remove the AppImage dir (to the script don't use the AppImage while indexing):
`rm -rf $HOME/AppImage`

**Comment by Gene-W** [comment]
Excellent, thank you! And after `rm -rf $HOME/AppImage` and `LogosIndexing.sh`, then use `change_Logos_to_native.sh` once more?

**Comment by ferion11** [comment]
No. The **change_Logos_to_native.sh** is just to change the installation made by AppImage to don't use Appimage anymore. You installed using **Install_Logos.sh** (that don't use AppImage), so you don't need it.
Now, after `rm -rf $HOME/AppImage`, you just need the `LogosIndexing.sh`, because the wine will be updated by the Manjaro, and Logos will be updated by itself. Somehow this looks better than before, humm :)

**Comment by Gene-W** [comment]
Just to share a quick update, Logos updated to 8.1.1 and reindexed successfully all within itself. It's still running, and running well. Thank you!

**Comment by ferion11** [comment]
Good to know. Thanks for the feedback too :)
