### ISSUE TITLE
Fix: ddr=gdi not working: update to newest winetricks

### ISSUE THREAD

**Issue by rik-shaw** [ferion11/LogosLinuxInstaller#8]
The flashing black boxes are because the "ddr=gdi" winetrick is "broken" in newer winetricks. It is a simple fix, you can either sed edit the winetricks script before running it to change "DirectDrawRenderer" to "renderer" for the key, or use regedit after winetricks to change the item. Reference: https://bugs.winehq.org/show_bug.cgi?id=47837

Note that ddr=gdi makes videos NOT play in Logos (I have never seen them play anyway..... still a bug we hope to solve)

UPDATE: winetricks master was just updated to fix this, so getting it should fix the issue: https://github.com/Winetricks/winetricks/issues/1542

**Comment by ferion11** [comment]
Thanks. I have tested the "opengl" too, because on the documentation today there is only "gdi" and "opengl". But that's is the first time that I remember seen the "renderer" option, so I will have to test it and understand what it's doing first (and the compatibility possible issues).
The documentation got one update too: "Removed in Wine 5.1.", so the next wine version update will have it.

**Comment by ferion11** [comment]
NOTE: I will have to make sure that the 2 configurations are there, because in case of update the winetricks don't make the update change.

**Comment by ferion11** [comment]
NOTE2: I tested the wine version 5.x for some time now, but I got worse performance than 4.21, and during one update I got an error that bugged my wine bottle and forced me to reinstall from scratch (using 4.21 now).

**Comment by ferion11** [comment]
Added the 2 at: cf4f6308bb888a0112b2c53ed5eec40c9bb90992
